    .balign 4
ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

    .balign 4
ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

    .balign 4
ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

    .balign 4
ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

    .balign 4
ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

    .balign 4
ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

    .balign 4
ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

    .balign 4
ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

    .balign 4
ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

    .balign 4
ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

    .balign 4
ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

    .balign 4
ProgrammableWaveData_12::
	.incbin "sound/programmable_wave_samples/12.pcm"

    .balign 4
ProgrammableWaveData_13::
	.incbin "sound/programmable_wave_samples/13.pcm"

    .balign 4
ProgrammableWaveData_14::
	.incbin "sound/programmable_wave_samples/14.pcm"

    .balign 4
ProgrammableWaveData_15::
	.incbin "sound/programmable_wave_samples/15.pcm"

    .balign 4
ProgrammableWaveData_16::
	.incbin "sound/programmable_wave_samples/16.pcm"

@ Unused
    .balign 4
ProgrammableWaveData_17::
	.incbin "sound/programmable_wave_samples/17.pcm"

@ Unused
    .balign 4
ProgrammableWaveData_18::
	.incbin "sound/programmable_wave_samples/18.pcm"

@ Unused
    .balign 4
ProgrammableWaveData_19::
	.incbin "sound/programmable_wave_samples/19.pcm"

@ Unused
    .balign 4
ProgrammableWaveData_20::
	.incbin "sound/programmable_wave_samples/20.pcm"

    .balign 4
ProgrammableWaveData_21::
	.incbin "sound/programmable_wave_samples/21.pcm"

    .balign 4
ProgrammableWaveData_22::
	.incbin "sound/programmable_wave_samples/22.pcm"

    .balign 4
ProgrammableWaveData_23::
	.incbin "sound/programmable_wave_samples/23.pcm"

    .balign 4
ProgrammableWaveData_24::
	.incbin "sound/programmable_wave_samples/24.pcm"

    .balign 4
ProgrammableWaveData_25::
	.incbin "sound/programmable_wave_samples/25.pcm"
